Refactor handlers
yiisoft/queue pull request #182
Opened 2023-12-25 09:02 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

Drop support pre-configured handlers, make it compatible with validator/hydrator handlers way

2023-12-25 14:04 UTC, samdark requested changes
The idea was that handler is not a PHP class string because worker could be implemented in non-PHP.

2023-12-26 07:02 UTC, xepozz commented
> The idea was that handler is not a PHP class string because worker could be implemented in non-PHP.

Already discussed in the internal chat.

There're should be routing outside a message to be able to work with different services across the one queue.

2023-12-26 07:30 UTC, samdark commented
With queue backends such as Redis, there's no external routing.

2023-12-26 08:17 UTC, samdark commented
Discussed internally. It makes sense if we'll introduce "message type decorator" and "message-based handlers" for messages in a separate PR.

@xepozz I guess docs should be adjusted, right?

2023-12-26 18:03 UTC, s1lver commented on src/Middleware/FailureHandling/Implementation/ExponentialDelayMiddleware.php
> +                handlerName: $message->getHandler(),
I think it should be also renamed in this case `handler: $message->getHandler(),`

2023-12-26 18:04 UTC, s1lver commented on src/Queue.php
> +            ['handlerName' => $message->getHandler()]
And here

2024-01-15 09:48 UTC, samdark approved these changes

2024-01-21 12:20 UTC, vjik requested changes

2024-01-21 12:20 UTC, vjik commented on src/Message/MessageInterface.php
> +     * @psalm-return class-string<MessageHandlerInterface>
Any string can be here (for example, ID for container), but class string only.

2024-01-21 12:20 UTC, vjik commented on README.md
> +    public function handle(\Yiisoft\Queue\Message\MessageInterface $downloadMessage): MessageInterface
```suggestion
    public function handle(\Yiisoft\Queue\Message\MessageInterface $downloadMessage): void
```

2024-01-21 12:20 UTC, vjik commented on README.md
> +        return $message;
```suggestion
```

2024-01-21 12:20 UTC, vjik commented on src/Message/EnvelopeTrait.php
> +        return $this->message->getHandler();
There may be a problem here, when handler support only original message and don't support envelope.

2024-11-24 14:55 UTC, closed without merging

2024-11-24 14:55 UTC, viktorprogger commented
Reimplemented in #218, which supports both cases:
- Handler class names as handler names for the case when a producer and a consumer are the same application. Now new can do `new Message(FooHandler::class, $data);`
- The old approach with preconfigured handler mapping for cases when an application is either a consumer or a producer, but not both.

With no additional routing.