Convert envelope trait to abstract class
yiisoft/queue pull request #231
Opened 2024-12-15 13:36 UTC by viktorprogger

2025-02-14 21:22 UTC, samdark approved these changes

2025-02-15 07:16 UTC, xepozz requested changes

2025-02-15 07:16 UTC, xepozz commented on src/Message/Envelope.php
> +    abstract protected function getEnvelopeMetadata(): array;
it's good to keep default empty array

2025-02-15 07:16 UTC, xepozz commented on src/Message/Message.php
> -    public function withMetadata(array $metadata): self
why?

2025-02-15 07:16 UTC, xepozz commented on src/Middleware/FailureHandling/FailureEnvelope.php
> +        private readonly array $failureMeta = [],
```suggestion
        private readonly array $metadata = [],
```

2025-02-15 07:16 UTC, xepozz commented on src/Message/Envelope.php
> -    public function withMessage(MessageInterface $message): self
why?

2025-02-15 07:16 UTC, xepozz commented on src/Middleware/FailureHandling/FailureEnvelope.php
> +        return [self::FAILURE_META_KEY => ArrayHelper::merge($this->message->getMetadata()[self::FAILURE_META_KEY] ?? [], $this->failureMeta)];
as you can see `getEnvelopeMetadata` method must provide all the collected metadata, not only the owned

2025-05-04 13:18 UTC, viktorprogger commented on src/Middleware/FailureHandling/FailureEnvelope.php
> +        return [self::FAILURE_META_KEY => ArrayHelper::merge($this->message->getMetadata()[self::FAILURE_META_KEY] ?? [], $this->failureMeta)];
For all metadata retrieval we have `Envelope::getMetadata()`. The `getEnvelopeMetadata()` method returns envelope metadata only.

2025-05-04 13:20 UTC, viktorprogger commented on src/Message/Envelope.php
> -    public function withMessage(MessageInterface $message): self
What's the real-world use case? I don't see any, that's why I removed this method.

2025-05-04 13:20 UTC, viktorprogger commented on src/Message/Message.php
> -    public function withMetadata(array $metadata): self
What's the real-world use case? I don't see any, that's why I removed this method.

2025-05-04 13:28 UTC, viktorprogger commented on src/Message/Envelope.php
> +    abstract protected function getEnvelopeMetadata(): array;
If metadata is empty - then there is no reason to create an envelope. So, every envelope should have its very own set of metadata attributes.

2025-05-11 16:07 UTC, vjik reviewed
Seems, this PR significantly degraded performance (see benchmark CI).

2025-05-13 08:42 UTC, samdark approved these changes

2025-05-13 08:42 UTC, samdark commented
The performance concern is valid.

2025-05-21 23:25 UTC, xepozz commented on src/Message/Message.php
> -    public function withMetadata(array $metadata): self
Message handlers may add metadata into the message

2025-07-13 13:39 UTC, viktorprogger commented
@samdark @vjik Envelope stack creation slowdown was fixed [here](https://github.com/yiisoft/queue/pull/231/commits/d676a3c11896e8aa6beef8dfac11b31df550d7e8).
My local bench result comparing to `master`:
<img width="1142" height="352" alt="image" src="https://github.com/user-attachments/assets/de044e00-4335-47be-9e61-9162227c68d2" />

2025-07-14 08:07 UTC, samdark commented
@viktorprogger benchmark is looking way better now. How about merging master into the PR branch?

2025-07-14 15:10 UTC, viktorprogger commented on src/Message/Message.php
> -    public function withMetadata(array $metadata): self
They should wrap it into an envelope then.

2025-07-14 15:13 UTC, viktorprogger commented on tests/Unit/Message/EnvelopeTraitTest.php
> -    public function testWithMessage(): void
Why is this better than `FooEnvelope::fromMessage($message)` or `new FooEnvelope()`?

2025-07-14 15:18 UTC, viktorprogger commented on src/Message/Envelope.php
> -    public function withMessage(MessageInterface $message): self
Another question.
Why is this better than `FooEnvelope::fromMessage($message)` or `new FooEnvelope()`?

2025-07-16 10:45 UTC, merged